---
kind: Template
apiVersion: v1
metadata:
  name: "ping-application"
  annotations:
    iconClass: "wildfly"
    description: "Sample App deployed on top of WildFly."
    tags: "devops-samples"
labels:
  createdBy: "ping-application-template"
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ping
    labels:
      app: ping
  spec:
    replicas: 1
    selector:
      app: ping
      deploymentconfig: ping
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: ping
          deploymentconfig: ping
      spec:
        containers:
        - name: ping
          image: ping
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping/api/time
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
            - ping
          from:
            kind: ImageStreamTag
            name: 'ping:latest'
            namespace: ping-example
        type: ImageChange
- kind: Service
  apiVersion: v1
  metadata:
    name: ping
    labels:
      app: ping
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: ping
    sessionAffinity: None
    type: ClusterIP
- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: ping
    labels:
      app: ping
  spec:
    host: ping.apps.example.com
    path: /ping/api/time
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ping
      weight: 100
    wildcardPolicy: None
