stages:
  - Build
  - Image

cache:
  key: "$CI_JOB_NAME"
  paths:
    - .m2/

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"
  VERSION: "1.0"
  APP_NAME: "ping"
  LOCAL_IMAGE: "gitlab-infra/ping"
  OKD_DOCKER_REGISTRY: "docker-registry.default.svc:5000"
  OKD_TARGET_NAMESPACE: "ping-example"
  OKD_REMOTE_IMAGE: "${OKD_DOCKER_REGISTRY}/${OKD_TARGET_NAMESPACE}/${APP_NAME}"

maven build:
  image: maven:3.6.0-jdk-8-slim
  stage: Build
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.war

docker build:
  image: docker:18.09.0
  stage: Image
  script:
    - docker build -t ${LOCAL_IMAGE}:${VERSION} -t ${LOCAL_IMAGE}:latest .
    - docker login -u okd -p ${OKD_TOKEN} ${OKD_DOCKER_REGISTRY}
    - docker tag ${LOCAL_IMAGE}:latest ${OKD_REMOTE_IMAGE}:latest
    - docker tag ${LOCAL_IMAGE}:latest ${OKD_REMOTE_IMAGE}:${VERSION}
    - docker push ${OKD_REMOTE_IMAGE}:latest
    - docker push ${OKD_REMOTE_IMAGE}:${VERSION}
