stages:
  - Build
  - Image

cache:
  key: "$CI_JOB_NAME"
  paths:
    - .m2/

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"
  VERSION: "1.0"
  APP_NAME: "ping"
  OKD_TARGET_NAMESPACE: "gitlab-infra"
  LOCAL_IMAGE: "gitlab-infra/ping"
  DOCKER_REGISTRY: "docker-registry.default.svc:5000"

maven build:
  image: maven:latest
  stage: Build
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.war

docker build:
  image: docker:stable
  stage: Image
  script:
    - docker build -t ${LOCAL_IMAGE}:${VERSION} -t ${LOCAL_IMAGE}:latest .
    - docker login -u okd -p ${OKD_TOKEN} ${DOCKER_REGISTRY}
    - docker tag ${LOCAL_IMAGE}:latest ${DOCKER_REGISTRY}/${OKD_TARGET_NAMESPACE}/${APP_NAME}:latest
    - docker tag ${LOCAL_IMAGE}:latest ${DOCKER_REGISTRY}/${OKD_TARGET_NAMESPACE}/${APP_NAME}:${VERSION}
    - docker push ${DOCKER_REGISTRY}/${OKD_TARGET_NAMESPACE}/${APP_NAME}:latest
    - docker push ${DOCKER_REGISTRY}/${OKD_TARGET_NAMESPACE}/${APP_NAME}:${VERSION}
